# Generated by Django 4.0.6 on 2022-07-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('IQD', 'IQD')], max_length=3, null=True),
        ),
    ]
