# Generated by Django 4.0.6 on 2022-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
